load plus.mat
Img_n=64*xn;
figure(1);
image(Img_n);
title("Original Image");
set(gcf,'Units','centimeter','Position',[2 2 10 10]);
key=input("输入：1进行无相位平移滤波，0进行有相位平移滤波");
%列滤波
OutImageButter_col_n=filt(b1,a1,Img_n,key);
OutImageRem_1col_n=filt(b2,a2,Img_n,key);
OutImageRem_2col_n=filt(b3,a3,Img_n,key);
%行滤波
OutImageButter_row_n=filt(b1,a1,Img_n',key);
OutImageButter_row_n=OutImageButter_row_n';
OutImageRem_1row_n=filt(b2,a2,Img_n',key);
OutImageRem_1row_n=OutImageRem_1row_n';
OutImageRem_2row_n=filt(b3,a3,Img_n',key);
OutImageRem_2row_n=OutImageRem_2row_n';
%plot
figure();
subplot(2,3,1);
image(OutImageButter_row_n);
title("Butter-Row")
subplot(2,3,4);
image(OutImageButter_col_n);
title("Butter-Col")
subplot(2,3,2);
image(OutImageRem_1row_n);
title("Remez-n2-Row")
subplot(2,3,5);
image(OutImageRem_1col_n);
title("Remez-n2-Col");
subplot(2,3,3);
image(OutImageRem_2row_n);
title("Remez-n3-Row");
subplot(2,3,6);
image(OutImageRem_2col_n);
title("Remez-n3-Col");
set(gcf,'Units','centimeter','Position',[2 2 30 20]);
%%
%%

% caculate
%1111111111
mse_br=CaculateMSE(Img,OutImageButter_row_n);
mse_bc=CaculateMSE(Img,OutImageButter_col_n);
mse_1r=CaculateMSE(Img,OutImageRem_1row_n);
mse_1c=CaculateMSE(Img,OutImageRem_1col_n);
mse_2r=CaculateMSE(Img,OutImageRem_2row_n);
mse_2c=CaculateMSE(Img,OutImageRem_2col_n);
mse_all=[mse_br,mse_bc,mse_1r,mse_1c,mse_2r,mse_2c];
%%1
pnsr_br=CaculatePNSR(Img,OutImageButter_row_n);
pnsr_bc=CaculatePNSR(Img,OutImageButter_col_n);
pnsr_1r=CaculatePNSR(Img,OutImageRem_1row_n);
pnsr_1c=CaculatePNSR(Img,OutImageRem_1col_n);
pnsr_2r=CaculatePNSR(Img,OutImageRem_2row_n);
pnsr_2c=CaculatePNSR(Img,OutImageRem_2col_n);
pnsr_all=[pnsr_br,pnsr_bc,pnsr_1r,pnsr_1c,pnsr_2r,pnsr_2c];
%%disp
disp("六个图片与没有噪声原始图像的的MSE分别为");
disp(mse_all);
disp("六个图片与没有噪声原始图像的的PNSR分别为");
disp(pnsr_all);
%2222222222222
% 先对行再对列
OutImageButter_col_n=filt(b1,a1,Img_n,key);
OutImageRem_1col_n=filt(b2,a2,Img_n,key);
OutImageRem_2col_n=filt(b3,a3,Img_n,key);
OutImageButter_n=filt(b1,a1,OutImageButter_col_n',key)';
OutImageRem_1_n=filt(b2,a2,OutImageRem_1col_n',key)';
OutImageRem_2_n=filt(b3,a3,OutImageRem_2col_n',key)';
%plot
figure(3);
subplot(1,3,1);
image(OutImageButter_n);title("Butter")
subplot(1,3,2);
image(OutImageRem_1_n);title("Remez-n2")
subplot(1,3,3);
image(OutImageRem_2_n);title("Remez-n3")
set(gcf,'Units','centimeter','Position',[2 2 30 10]);
%%
figure(4);
imshow(angle(fft2(Img_n)));title("Original Angle Phase")
set(gcf,'Units','centimeter','Position',[2 2 20 20]);
figure(5);
subplot(3,3,1);
imshow(angle(fft2(OutImageButter_n)));title("Butter")
subplot(3,3,2);
imshow(angle(fft2(OutImageRem_1_n)));title("Remez-n2")
subplot(3,3,3);
imshow(angle(fft2(OutImageRem_2_n)));title("Remez-n3")
subplot(3,3,4);
imshow(angle(fft2(OutImageButter_row_n)));title("Butter-Row")
subplot(3,3,5);
imshow(angle(fft2(OutImageRem_1row_n)));title("Remez-n2-Row")
subplot(3,3,6);
imshow(angle(fft2(OutImageRem_2row_n)));title("Remez-n3-Row")
subplot(3,3,7);
imshow(angle(fft2(OutImageButter_col_n)));title("Butter-Col")
subplot(3,3,8);
imshow(angle(fft2(OutImageRem_1col_n)));title("Remez-n2-Col");
subplot(3,3,9);
imshow(angle(fft2(OutImageRem_2col_n)));title("Remez-n3-Col");
%caculate
%2
mse_b_n=CaculateMSE(Img,OutImageButter_n);
mse_1_n=CaculateMSE(Img,OutImageRem_1_n);
mse_2_n=CaculateMSE(Img,OutImageRem_2_n);
mse_all_n=[mse_b_n,mse_1_n,mse_2_n];
pnsr_b_n=CaculatePNSR(Img,OutImageButter_n);
pnsr_1_n=CaculatePNSR(Img,OutImageRem_1_n);
pnsr_2_n=CaculatePNSR(Img,OutImageRem_2_n);
pnsr_all_n=[pnsr_b_n,pnsr_1_n,pnsr_2_n];
disp("三个图像与原本没有噪声图像的MSE");
disp(mse_all_n);
disp("三个图像与原本没有噪声图像的PNSR");
disp(pnsr_all_n);