load plus.mat
Img=64*x;
key=input("输入：1进行无相位平移滤波，0进行有相位平移滤波");
figure(1);
image(Img);
title("Original Image");
set(gcf,'Units','centimeter','Position',[2 2 10 10]);
%%分别对行再对列
%列滤波
OutImageButter_col=filt(b1,a1,Img,key);
OutImageRem_1col=filt(b2,a2,Img,key);
OutImageRem_2col=filt(b3,a3,Img,key);
%行滤波
OutImageButter_row=filt(b1,a1,Img',key);
OutImageButter_row=OutImageButter_row';
OutImageRem_1row=filt(b2,a2,Img',key);
OutImageRem_1row=OutImageRem_1row';
OutImageRem_2row=filt(b3,a3,Img',key);
OutImageRem_2row=OutImageRem_2row';
%plot
figure(2);
subplot(2,3,1);
image(OutImageButter_row);
title("Butter-Row");
subplot(2,3,4);
image(OutImageButter_col);
title("Butter-Col");
subplot(2,3,2);
image(OutImageRem_1row);
title("Remez-n2-Row");
subplot(2,3,5);
image(OutImageRem_1col);
title("Remez-n2-Col");
subplot(2,3,3);
image(OutImageRem_2row);
title("Remez-n3-Row");
subplot(2,3,6);
image(OutImageRem_2col);
title("Remez-n3-Col");
set(gcf,'Units','centimeter','Position',[2 2 30 20]);

%%先对行，后对列
OutImageButter_col=filt(b1,a1,Img,key);
OutImageRem_1col=filt(b2,a2,Img,key);
OutImageRem_2col=filt(b3,a3,Img,key);
OutImageButter=filt(b1,a1,OutImageButter_col',key)';
OutImageRem_1=filt(b2,a2,OutImageRem_1col',key)';
OutImageRem_2=filt(b3,a3,OutImageRem_2col',key)';
%plot
figure(3);
subplot(1,3,1);
image(OutImageButter);title("Butter")
subplot(1,3,2);
image(OutImageRem_1);title("Remez-n2")
subplot(1,3,3);
image(OutImageRem_2);title("Remez-n3")
set(gcf,'Units','centimeter','Position',[5 5 30 8]);
%end
figure(4);
OutImageButter_FFT=fft2(OutImageButter);
OutImageRem_1_FFT=fft2(OutImageRem_1);
OutImageRem_2_FFT=fft2(OutImageRem_2);
%%
OutImageButter_row_FFT=fft2(OutImageButter_row);
OutImageButter_col_FFT=fft2(OutImageButter_col);
OutImageRem_1row_FFT=fft2(OutImageRem_1row);
OutImageRem_1col_FFT=fft2(OutImageRem_1col);
OutImageRem_2row_FFT=fft2(OutImageRem_2row);
OutImageRem_2col_FFT=fft2(OutImageRem_2col);
subplot(3,3,4);
imshow(angle(OutImageButter_row_FFT));title("Butter-Row");
subplot(3,3,5);
imshow(angle(OutImageRem_1row_FFT));title("Remez-n2-Row");
subplot(3,3,6);
imshow(angle(OutImageRem_2row_FFT));title("Remez-n3-Row");

subplot(3,3,7);
imshow(angle(OutImageButter_col_FFT));title("Butter-Col");
subplot(3,3,8);
imshow(angle(OutImageRem_1col_FFT));title("Remez-n2-Col");
subplot(3,3,9);
imshow(angle(OutImageRem_2col_FFT));title("Remez-n3-Col");
colorbar;
%%
OutImageButter_FFT_Angle=angle(OutImageButter_FFT);
OutImageRem_1_FFT_Angle=angle(OutImageRem_1_FFT);
OutImageRem_2_FFT_Angle=angle(OutImageRem_2_FFT);
subplot(3,3,1);
imshow(OutImageButter_FFT_Angle);title("Butter")
subplot(3,3,2);
imshow(OutImageRem_1_FFT_Angle);title("Remez-n2")
subplot(3,3,3);
imshow(OutImageRem_2_FFT_Angle);title("Remez-n3")
set(gcf,'Units','centimeter','Position',[1 0 20 10]);
%
figure(5);
imshow(angle(fft(Img)));title("Original Angle Phase");
set(gcf,'Units','centimeter','Position',[1 0 10 10]);
%
figure();
Img_delta=zeros(size(Img));
Img_delta(1,:)=1;
Img_delta(:,1)=1;
[m,n]=meshgrid(1:size(Img_delta));

img_butter_col=filter(b1,a1,Img_delta);
img_remez1_col=filter(b2,a2,Img_delta);
img_remez2_col=filter(b3,a3,Img_delta);
img_butter_row=filter(b1,a1,Img_delta')';
img_remez1_row=filter(b2,a2,Img_delta')';
img_remez2_row=filter(b3,a3,Img_delta')';
img_butter=filter(b1,a1,img_butter_col')';
img_remez1=filter(b2,a2,img_remez1_col')';
img_remez2=filter(b3,a3,img_remez2_col')';
subplot(3,3,1);
meshc(m,n,img_butter);title("Butter")
subplot(3,3,2);
meshc(m,n,img_remez1);title("Remez-n2")
subplot(3,3,3);
meshc(m,n,img_remez2);title("Remez-n3")
subplot(3,3,4);
meshc(m,n,img_butter_row);title("Butter-Row");
subplot(3,3,5);
meshc(m,n,img_remez1_row);title("Remez-n2-Row");
subplot(3,3,6);
meshc(m,n,img_remez2_row);title("Remez-n3-Row");
subplot(3,3,7);
meshc(m,n,img_butter_col);title("Butter-Col");
subplot(3,3,8);
meshc(m,n,img_remez1_col);title("Remez-n2-Col");
subplot(3,3,9);
meshc(m,n,img_remez2_col);title("Remez-n3-Col");

figure()
subplot(3,3,1);
imshow(angle(fft2(img_butter)));title("Butter")
subplot(3,3,2);
imshow(angle(fft2(img_remez1)));title("Remez-n2")
subplot(3,3,3);
imshow(angle(fft2(img_remez2)));title("Remez-n3")
subplot(3,3,4);
imshow(angle(fft2(img_butter_row)));title("Butter-Row");
subplot(3,3,5);
imshow(angle(fft2(img_remez1_row)));title("Remez-n2-Row");
subplot(3,3,6);
imshow(angle(fft2(img_remez2_row)));title("Remez-n3-Row");
subplot(3,3,7);
imshow(angle(fft2(img_butter_col)));title("Butter-Col");
subplot(3,3,8);
imshow(angle(fft2(img_remez1_col)));title("Remez-n2-Col");
subplot(3,3,9);
imshow(angle(fft2(img_remez2_col)));title("Remez-n3-Col");
