%%
mse_br=CaculateMSE(Img,OutImageButter_row);
mse_bc=CaculateMSE(Img,OutImageButter_col);
mse_1r=CaculateMSE(Img,OutImageRem_1row);
mse_1c=CaculateMSE(Img,OutImageRem_1col);
mse_2r=CaculateMSE(Img,OutImageRem_2row);
mse_2c=CaculateMSE(Img,OutImageRem_2col);
mse_b=CaculateMSE(Img,OutImageButter);
mse_1=CaculateMSE(Img,OutImageRem_1);
mse_2=CaculateMSE(Img,OutImageRem_2);
mse_all=[mse_b,mse_1,mse_2,mse_br,mse_bc,mse_1r,mse_1c,mse_2r,mse_2c];
%%
pnsr_b=CaculatePNSR(Img,OutImageButter);
pnsr_1=CaculatePNSR(Img,OutImageRem_1);
pnsr_2=CaculatePNSR(Img,OutImageRem_2);
pnsr_br=CaculatePNSR(Img,OutImageButter_row);
pnsr_bc=CaculatePNSR(Img,OutImageButter_col);
pnsr_1r=CaculatePNSR(Img,OutImageRem_1row);
pnsr_1c=CaculatePNSR(Img,OutImageRem_1col);
pnsr_2r=CaculatePNSR(Img,OutImageRem_2row);
pnsr_2c=CaculatePNSR(Img,OutImageRem_2col);
pnsr_all=[pnsr_b,pnsr_1,pnsr_2,pnsr_br,pnsr_bc,pnsr_1r,pnsr_1c,pnsr_2r,pnsr_2c];
%%disp
disp("九个图片与原始图像的的MSE分别为");
disp(mse_all);
disp("九个图片与原始图像的的PNSR分别为");
disp(pnsr_all);